
services:
  - type: web
    runtime: node
    name: backend
    plan: free
    rootDir: ./backend
    buildCommand: npm install
    startCommand: node server.js
    repo: https://github.com/BeOct1/betmora-movie-app.git  
    branch: main 
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        value: mongodb+srv://bitrusmail:7gXJHQGiPR9mfBab@cluster0.1sgoxgf.mongodb.net/bitrusmail?retryWrites=true&w=majority
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
