
services:
  - type: web
    name: frontend
    env: static
    staticPublishPath: ./frontend/dist
    routes:
      - path: /*
        dest: /index.html

  - type: web
    name: backend
    env: node
    plan: free
    repo: https://github.com/Bit-Ed/BeMora-Movie-App.git # Change this to your repo URL
    branch: main # Change this to your branch name
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        fromDatabase:
          name: betmoramovieapp
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
