name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run Frontend Linter
        run: npm run lint
        working-directory: ./frontend

      - name: Run Frontend Tests
        run: npm test
        working-directory: ./frontend

      - name: Install Backend Dependencies
        run: npm install
        working-directory: ./backend

      - name: Run Backend Linter
        run: npm run lint
        working-directory: ./backend

      - name: Run Backend Tests
        run: npm test
        working-directory: ./backend
